CREATE TABLE `enterprise_info` (
                                   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
                                   `enterprise_name` varchar(255) NOT NULL DEFAULT '' COMMENT '企业名称',
                                   `credit_code` varchar(18) NOT NULL DEFAULT '' COMMENT '统一社会信用代码',
                                   `legal_person` varchar(100) DEFAULT '' COMMENT '法定代表人',
                                   `registered_capital` varchar(100) DEFAULT '' COMMENT '注册资本',
                                   `establishment_date` date DEFAULT NULL COMMENT '成立日期',
                                   `registration_status` varchar(50) DEFAULT '' COMMENT '登记状态',
                                   `registered_address` varchar(512) DEFAULT '' COMMENT '注册地址',
                                   `province` varchar(100) DEFAULT '' COMMENT '所属省份',
                                   `city` varchar(100) DEFAULT '' COMMENT '所属城市',
                                   `district` varchar(100) DEFAULT '' COMMENT '所属区县',
                                   `phone` varchar(512) DEFAULT '' COMMENT '有效手机号',
                                   `more_phones` varchar(512) DEFAULT '' COMMENT '更多电话',
                                   `email` varchar(255) DEFAULT '' COMMENT '邮箱',
                                   `org_type` varchar(255) DEFAULT '' COMMENT '企业(机构)类型',
                                   `tax_id` varchar(100) DEFAULT '' COMMENT '纳税人识别号',
                                   `reg_number` varchar(100) DEFAULT '' COMMENT '注册号',
                                   `org_code` varchar(100) DEFAULT '' COMMENT '组织机构代码',
                                   `insured_count` int(11) DEFAULT NULL COMMENT '参保人数',
                                   `report_year` varchar(50) DEFAULT '' COMMENT '参保人数所属年报',
                                   `business_term` varchar(100) DEFAULT '' COMMENT '营业期限',
                                   `industry_gb_category` varchar(100) DEFAULT '' COMMENT '国标行业门类',
                                   `industry_gb_major` varchar(100) DEFAULT '' COMMENT '国标行业大类',
                                   `industry_gb_medium` varchar(100) DEFAULT '' COMMENT '国标行业中类',
                                   `industry_gb_minor` varchar(100) DEFAULT '' COMMENT '国标行业小类',
                                   `industry_qcc_category` varchar(100) DEFAULT '' COMMENT '企查查行业门类',
                                   `industry_qcc_major` varchar(100) DEFAULT '' COMMENT '企查查行业大类',
                                   `industry_qcc_medium` varchar(100) DEFAULT '' COMMENT '企查查行业中类',
                                   `industry_qcc_minor` varchar(100) DEFAULT '' COMMENT '企查查行业小类',
                                   `enterprise_scale` varchar(100) DEFAULT '' COMMENT '企业规模',
                                   `former_names` varchar(1024) DEFAULT '' COMMENT '曾用名',
                                   `english_name` varchar(255) DEFAULT '' COMMENT '英文名',
                                   `website` varchar(512) DEFAULT '' COMMENT '官网网址',
                                   `mailing_address` varchar(512) DEFAULT '' COMMENT '通信地址',
                                   `mailing_zipcode` varchar(20) DEFAULT '' COMMENT '通信地址邮编',
                                   `introduction` text COMMENT '企业简介',
                                   `business_scope` text COMMENT '经营范围',
                                   `create_by` varchar(64) DEFAULT '' COMMENT '创建人ID',
                                   `update_by` varchar(64) DEFAULT '' COMMENT '修改人ID',
                                   `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                   `del_flag` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否删除：0.否，1.是',
                                   `main_enterprise_flag` tinyint(1) DEFAULT '0' COMMENT '是否于“10+1”产业链主企业名单内',
                                   PRIMARY KEY (`id`) USING BTREE,
                                   KEY `idx_enterprise_name` (`enterprise_name`) USING BTREE,
                                   KEY `idx_credit_code` (`credit_code`) USING BTREE,
                                   KEY `idx_reg_number` (`reg_number`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=272589 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='企业信息表-企查查';